### ISSUE TITLE
Hide time

### ISSUE THREAD

**Issue by stella-di** [miamarti/ngcalendar#2]
How to hide time in ngCalendar?

**Comment by miamarti** [comment]
Hi @stella-di,

Unfortunately there is not an attribute that makes this action automatically.
However you can remove it with css. See the example below:

`
.dhtmlxcalendar_material.dhtmlxcalendar_in_input div.dhtmlxcalendar_time_cont {
  display:none !important;
}
`

If you prefer, we can establish a dialogue through the chat https://gitter.im/miamarti/ng-calendar
