### ISSUE TITLE
Calendar shows behind modal

### ISSUE THREAD

**Issue by LuisEGR** [miamarti/ngcalendar#3]
Trying to put the calendar inside a modal this shows on the back, I was looking for the problem and seems to be:

inline-style
z-index: 105;

`<div class="dhtmlxcalendar_material dhtmlxcalendar_in_input" style="visibility: visible; left: 813px; top: 637px; z-index: 105;"> ... </div>`

changing this 105 to 99999 this is solved.

**Comment by miamarti** [comment]
Hi @LuisEGR ,

Infelixmente this value is dynamically created by:
this.base.style.zIndex = window.dhx4.zim.reserve (this.conf.z ...

I recommend inject an overlay to this z-index in its application, in a timely manner.
Anyway, thank you for the support
